function DecodeTriggers(triggers)
    local decoded_str = {}
    table.insert(decoded_str, "-- This text is generated by TrigEditPlus\n")

    for i = 1, #triggers do
        if #(trigger.players) == 0 then
            -- Do special trigger processings here
        else
            table.insert(decoded_str, DecodeTrigger(trigger))
        end
    end

    return table.concat(decoded_str, "\n")
end
